version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/nextjsbatch
    depends_on:
      - postgres
    command: sh -c "npx prisma migrate dev && npm run dev"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: nextjsbatch
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
